name: Deploy Pipeline

on:
  push:
    branches:
      - '**'
    # Solo ejecutar cuando hay un PR abierto para la rama
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'
      - 'docs/**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  checkout:
    name: Checkout Repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 